# Generated by Django 6.0.3 on 2026-03-12 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompositionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("synopsis", models.TextField(blank=True, default="")),
                ("doc_type", models.CharField(default="novel", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("order_no", models.IntegerField()),
                ("time_start", models.BigIntegerField(blank=True, null=True)),
                ("time_end", models.BigIntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={"ordering": ["order_no"],},
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="intent",
                        serialize=False,
                        to="core.document",
                    ),
                ),
                ("genre", models.CharField(blank=True, default="", max_length=100)),
                ("theme_or_claim", models.TextField(blank=True, default="")),
                ("core_values", models.TextField(blank=True, default="")),
                ("constraints", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
