from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('upload', views.upload_document, name='upload_document'),
    path('document/create', views.document_create, name='document_create'),
    path('document/<str:doc_id>/delete', views.delete_document, name='delete_document'),
    path('document/<str:doc_id>/intent', views.intent_update, name='intent_update'),
    path('document/<str:doc_id>/', views.document_detail, name='document_detail'),
    path('document/<str:doc_id>/download', views.download_document, name='download_document'),
    path('document/<str:doc_id>/generate_proposals', views.generate_proposals, name='generate_proposals'),
    path('document/<str:doc_id>/save_selection', views.save_selection, name='save_selection'),
    path('document/<str:doc_id>/generate_composition', views.generate_composition, name='generate_composition'),
    path('api/document/<str:doc_id>/manuscript_data', views.manuscript_data, name='manuscript_data'),
    path('api/document/<str:doc_id>/save_manuscript', views.save_manuscript, name='save_manuscript'),
    path('api/document/<str:doc_id>/generate_draft', views.generate_draft, name='generate_draft'),
    path('api/document/<str:doc_id>/save_draft_configs', views.save_draft_configs, name='save_draft_configs'),
    path('document/<str:doc_id>/evaluate', views.evaluate_start, name='evaluate_start'),
    path('document/<str:doc_id>/evaluate/stream', views.evaluate_stream, name='evaluate_stream'),
    path('document/<str:doc_id>/calculate_energy', views.calculate_energy, name='calculate_energy'),
    path('document/<str:doc_id>/quantum_optimize', views.quantum_optimize, name='quantum_optimize'),
    path('document/<str:doc_id>/save_manual_selection', views.save_manual_selection, name='save_manual_selection'),
    path('api/document/<str:doc_id>/save', views.api_save_document, name='api_save_document'),
    path('api/draft/update', views.draft_update, name='draft_update'),
    path('api/draft/delete', views.draft_delete, name='draft_delete'),
    path('api/draft/get', views.draft_get, name='draft_get'),
    path('api/draft/list', views.draft_list, name='draft_list'),
    path('save_servers_config', views.save_servers_config, name='save_servers_config'),
    path('api/save_servers_config', views.save_servers_config, name='api_save_servers_config'),
    path('update_suggestion_count', views.update_suggestion_count, name='update_suggestion_count'),
    path('api/update_suggestion_count', views.update_suggestion_count, name='api_update_suggestion_count'),
    path('load_server_settings', views.load_server_settings, name='load_server_settings'),
    path('help/gemini-api', views.help_gemini_api, name='help_gemini_api'),
    path('help/amplify-api', views.help_amplify_api, name='help_amplify_api'),
    path('usage', views.usage, name='usage'),
]
